create table
  public.Posts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    content text not null,
    author uuid not null,
    constraint Posts_pkey primary key (id),
    constraint Posts_author_fkey foreign key (author) references profiles (id) on delete cascade
  ) tablespace pg_default;